[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  adafruit/Adafruit BME280 Library
  adafruit/Adafruit Unified Sensor
  paulstoffregen/OneWire
  milesburton/DallasTemperature
build_flags =
  -D CORE_DEBUG_LEVEL=1
